### ISSUE TITLE
Please clarify console.log

### ISSUE THREAD

**Issue by revelt** [olov/ast-traverse#1]
In "Usage" section, you're just putting:

```
console.log();
```

I suspect that's an error. Please post working `console.log()`'s because it's difficult to understand to less experienced developers.

**Comment by olov** [comment]
The example in usage is entirely executable, try it out if you like. The `console.log();` is just there to provide an newline between the different sections. I'm sorry that you find the example difficult to understand but I have no plans of providing further documentation and/or examples for this library.

**Comment by revelt** [comment]
Aha! Thanks for clarification. I was expecting something within `console.log()` and after all it's just newline.
